apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: replicaset
    tier: replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: replicaset
  template:
    metadata:
      labels:
        tier: replicaset
    spec:
      containers:
      - name: server
        image: sergii703/frontend
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "Test"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"
        - name: AD_SERVICE_ADDR
          value: "adservice:9555"

