apiVersion: v1
kind: Pod
metadata:
  name: 'web'
  labels:
    key: 'app'

spec:
  containers:
  - name: web
    image: sergii703/web-image
    volumeMounts:
    - name: web
      mountPath: /app
  
  initContainers:
  - name: init-web
    image: busybox:1.31.0
    volumeMounts:
    - name: web
      mountPath: /app
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
  
  volumes:
  - name: web
    emptyDir: {}


